### PR TITLE
[WIP] - Renamed clause files, modified files to match changes

### PR DESCRIPTION
**Pull request by cemremengu**
Renaming clause files to be consistent & explicit

### CODE REVIEW

**Comment by cemremengu** [comment]
Why doesn't the tests run here ? 😞

**Comment by eejdoowad** [comment]
Sorry, I ended up separating SQL related functionality out of sqorn-core and into sqorn-sql. Any chance you can update the PR accordingly?

This should hopefully be the last major reorganization. I need to figure out what I broke in travis.

**Comment by cemremengu** [comment]
No problem organization is important. I want to make sure tests are in good shape before this.

There is a file `old.test.js` under `misc` which seems to fail for me. Is the naming correct or they should be removed?

**Comment by eejdoowad** [comment]
`old.test.js` contains random old queries. Its tests should all pass. I'm guessing they failed because you changed some method names: return => returning, order => orderby, group => groupby.

Can you preserve the old method names?

**Comment by cemremengu** [comment]
Oh ok I see. I will probably close this PR and start over.

One more thing, do you mind removing/ignoring lock files? They change and will conflict with the current ones when I push. I think its best if you do the change so I will be in sync with you.

**Comment by eejdoowad** [comment]
I've fixed Travis. Submitted a PR removing lock files, but it looks like there some CI issues. Will get back to this tomorrow.

**Pull request closed without merging**
